name: YouTube Live
on:
  schedule:
    - cron: '0 0/3 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Get beINSportsHaber
      run: |
        touch ./spor/beinsportshaber.m3u8
        sudo cat >./spor/beinsportshaber.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/channel/UCPe9vNjHF1kEExT5kHwc7aw/live)
        EOL

    - name: Get SozcuTV
      run: |
        touch ./haber/sozcutv.m3u8
        sudo cat >./haber/sozcutv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@Sozcutelevizyonu/live)
        EOL

    - name: Get HaberturkTV
      run: |
        touch ./haber/haberturktv.m3u8
        sudo cat >./haber/haberturktv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@haberturktv/live)
        EOL  

    - name: Get NTV
      run: |
        touch ./haber/ntv.m3u8
        sudo cat >./haber/ntv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@NTV/live)
        EOL        

    - name: Get HalkTV
      run: |
        touch ./haber/halktv.m3u8
        sudo cat >./haber/halktv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@Halktvkanali/live)
        EOL

    - name: Get Tele1
      run: |
        touch ./haber/tele1.m3u8
        sudo cat >./haber/tele1.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@Tele1comtr/live)
        EOL 

    - name: Get KRT
      run: |
        touch ./haber/krt.m3u8
        sudo cat >./haber/krt.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@krtcanli/live)
        EOL           

    - name: Get BloombergHT
      run: |
        touch ./haber/bloomberght.m3u8
        sudo cat >./haber/bloomberght.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@BloombergHT/live)
        EOL           
        
    - name: Get Ekoturk
      run: |
        touch ./haber/ekoturk.m3u8
        sudo cat >./haber/ekoturk.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@EKOTURKTV/live)
        EOL 

    - name: Get TV100
      run: |
        touch ./haber/tv100.m3u8
        sudo cat >./haber/tv100.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@tv100/live)
        EOL         
      
    - name: Get ShowTV
      run: |
        touch ./ulusal/showtv.m3u8
        sudo cat >./ulusal/showtv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@showtv/live)
        EOL     

    - name: Get ATV
      run: |
        touch ./ulusal/atv.m3u8
        sudo cat >./ulusal/atv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@atvturkiye/live)
        EOL   
        
    - name: Get TRT1
      run: |
        touch ./ulusal/trt1.m3u8
        sudo cat >./ulusal/trt1.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@trt1/live)
        EOL
        
    - name: Get StarTV
      run: |
        touch ./ulusal/startv.m3u8
        sudo cat >./ulusal/startv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@StarTVResmi/live)
        EOL

    - name: Get PalStation
      run: |
        touch ./muzik/palstation.m3u8
        sudo cat >./muzik/palstation.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=6-GnbjMkmGc)
        EOL        
        
    - name: Get ASpor
      run: |
        touch ./spor/aspor.m3u8
        sudo cat >./spor/aspor.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@ASpor/live)
        EOL

    - name: Get TayTv
      run: |
        touch ./spor/taytv.m3u8
        sudo cat >./spor/taytv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@TayTvOfficial/live)
        EOL

    - name: Get AHaber
      run: |
        touch ./haber/ahaber.m3u8
        sudo cat >./haber/ahaber.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/ahaber/live)
        EOL

    - name: Get APara
      run: |
        touch ./haber/apara.m3u8
        sudo cat >./haber/apara.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/channel/UCzrGg6iyRDuUSnO0cQ5oLcA/live)
        EOL

    - name: Get Sirinler
      run: |
        touch ./cocuk/sirinler.m3u8
        sudo cat >./cocuk/sirinler.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@sirinler/live)
        EOL

    - name: git add
      run: |
        git add -A
        ls -la

    - name: commit & push
      run: |
        git commit -m "links are updated"
        git push
